package inventory.model;
// Generated Dec 26, 2018 6:59:18 PM by Hibernate Tools 5.1.10.Final

import java.math.BigDecimal;
import java.util.Date;

/**
 * History generated by hbm2java
 */
public class HistoryDTO implements java.io.Serializable {

	private int id;
	private ProductInfoDTO productInfo;
	private String actionName;
	private int type;
	private int quantity;
	private BigDecimal price;
	private int activeFlag;
	private Date createDate;
	private Date updateDate;

	public HistoryDTO() {
	}

	public HistoryDTO(ProductInfoDTO productInfo, String actionName, int type, int quantity, BigDecimal price, int activeFlag,
			Date createDate, Date updateDate) {
		this.productInfo = productInfo;
		this.actionName = actionName;
		this.type = type;
		this.quantity = quantity;
		this.price = price;
		this.activeFlag = activeFlag;
		this.createDate = createDate;
		this.updateDate = updateDate;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public ProductInfoDTO getProductInfo() {
		return this.productInfo;
	}

	public void setProductInfo(ProductInfoDTO productInfo) {
		this.productInfo = productInfo;
	}

	public String getActionName() {
		return this.actionName;
	}

	public void setActionName(String actionName) {
		this.actionName = actionName;
	}

	public int getType() {
		return this.type;
	}

	public void setType(int type) {
		this.type = type;
	}

	public int getQuantity() {
		return this.quantity;
	}

	public void setQuantity(int quantity) {
		this.quantity = quantity;
	}

	public BigDecimal getPrice() {
		return this.price;
	}

	public void setPrice(BigDecimal price) {
		this.price = price;
	}

	public int getActiveFlag() {
		return this.activeFlag;
	}

	public void setActiveFlag(int activeFlag) {
		this.activeFlag = activeFlag;
	}

	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

}
