package inventory.model;
// Generated Dec 26, 2018 6:59:18 PM by Hibernate Tools 5.1.10.Final

import java.util.Date;

/**
 * ProductInStock generated by hbm2java
 */
public class ProductInStockDTO implements java.io.Serializable {

	private int id;
	private ProductInfoDTO productInfo;
	private int quantity;
	private int activeFlag;
	private Date createDate;
	private Date updateDate;

	public ProductInStockDTO() {
	}

	public ProductInStockDTO(ProductInfoDTO productInfo, int quantity, int activeFlag, Date createDate, Date updateDate) {
		this.productInfo = productInfo;
		this.quantity = quantity;
		this.activeFlag = activeFlag;
		this.createDate = createDate;
		this.updateDate = updateDate;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public ProductInfoDTO getProductInfo() {
		return this.productInfo;
	}

	public void setProductInfo(ProductInfoDTO productInfo) {
		this.productInfo = productInfo;
	}

	public int getQuantity() {
		return this.quantity;
	}

	public void setQuantity(int quantity) {
		this.quantity = quantity;
	}

	public int getActiveFlag() {
		return this.activeFlag;
	}

	public void setActiveFlag(int activeFlag) {
		this.activeFlag = activeFlag;
	}

	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

}
